### PR TITLE
Enforce a npm version with non breaking changes

### PR DESCRIPTION
**Pull request by jerome-benoit**
Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>

### CODE REVIEW

**Review by LucasBrazi06 — APPROVED** [review]
Got it, just downgraded to npm 6 / node 12

**Comment by jerome-benoit** [comment]
> Got it, just downgraded to npm 6 / node 12

The current LTS is 14.x and is shipped with npm version 6.x. Unless you intentionally upgrade npm to 7.x, a current LTS just works with brew install node@14.

**Comment by LucasBrazi06** [comment]
> The current LTS is 14.x and is shipped with npm version 6.x. Unless you intentionally upgrade npm to 7.x, a current LTS installation just works with `brew install node@14`.

I did 'brew install node' and got npm 7 + node 15.

**Comment by LucasBrazi06** [comment]
I installed node 12 because I saw this in the package.json:

image

**Comment by jerome-benoit** [comment]
> > The current LTS is 14.x and is shipped with npm version 6.x. Unless you intentionally upgrade npm to 7.x, a current LTS installation just works with `brew install node@14`.

> I did 'brew install node' and got npm 7 + node 15.

The command is `brew install node@14`. `node` refer always to the current non LTS version with brew. 

An node version upgrade to current LTS shall be done in the repos ...

**Pull request merged**
